version: '2'

services:
  db:
    image: tobi312/rpi-mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: nextcloud_root_password
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud_password
      MYSQL_DATABASE: nextcloud
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    ports:
      - "3306:3306"
    volumes:
      - /Users/liudeshan/work/learning/docker/code/nextcloud_demo/nextcloud/db:/var/lib/mysql

  web:
    image: arm64v8/nextcloud:latest
    environment:
      - MYSQL_PASSWORD=nextcloud_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    links:
      - db
    ports:
      - "8080:80"
    volumes:
      - /Users/liudeshan/work/learning/docker/code/nextcloud_demo/nextcloud/html:/var/www/html
