version: '2'

services:
  db:
    image: tobi312/rpi-mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: filerun_root_password
      MYSQL_USER: filerun
      MYSQL_PASSWORD: filerun_password
      MYSQL_DATABASE: filerun
      MYSQL_TCP_PORT: 3308
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    ports:
    - 3308:3308
    expose:
      - 3308
    volumes:
      - /Users/liudeshan/work/learning/docker/code/filerun_demo/filerun/db:/var/lib/mysql

  web:
    image: filerun/filerun:arm64v8
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3308
      FR_DB_NAME: filerun
      FR_DB_USER: filerun
      FR_DB_PASS: filerun_password
      APACHE_RUN_USER: pi
      APACHE_RUN_USER_ID: 1000
      APACHE_RUN_GROUP: pi
      APACHE_RUN_GROUP_ID: 1000
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8081:80"
    volumes:
      - /Users/liudeshan/work/learning/docker/code/filerun_demo/filerun/html:/var/www/html
      - /Users/liudeshan/work/learning/docker/code/filerun_demo/filerun/user-files:/user-files
